[package]
name = "chippy8"
version = "0.1.0"
authors = ["Amandus Søve Thorsrud <ama.thorsrud@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
pixels = "0.0.4"
winit = "0.22.2"
rand = "0.7.3"
